# Generated by Django 4.0.2 on 2022-02-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
